name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_USERNAME: ${{ secrets.USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:  
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: johndoetester
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: johndoetester/openliberty:latest
